### PR TITLE
Update index.html.pm to link to Current list of sponsors

### PR DESCRIPTION
**Pull request by spdegabrielle**
Only gh sponsors provides a mechanism for recording consent to list sponsors. We are looking into doing this for SFC sponsors and donors but we don't currently have a way to record consent to publicly thank them by name.

### CODE REVIEW

**Comment by spdegabrielle** [comment]
also deleting orphan page.
#289

**Comment by spdegabrielle** [comment]
I don’t think there is a way of fixing the page at this stage. While we potentially can get a list of donors from SFC, we don’t have contact details.

Even when we do have contact details it is time consuming and not effective. I would like to acknowledge the SFC donations but I can’t justify my effort, or commit to updating it on an ongoing basis.

**Comment by sorawee** [comment]
I would be happy to continue updating the page, provided that:

- the Racket management trusts me to handle the donation information. I believe @rfindler was the one who fetched the initial data a couple of years ago, so maybe I can talk with him directly?
- @spdegabrielle helped me detailing the steps that he did when the page was first created.
- there's an `@racket-lang.org`  account that I can use (I don't want to use my personal Gmail for this)

I believe the task can be mostly automated (web scraping + mail merge). I can't guarantee that I will get it done to coincide with this release though

**Comment by spdegabrielle** [comment]
@sorawee 
i used the list of names to search for  email addresses, 

I used a form asking for consent via email (20-Aug-2020):
```
Hi,
 
You have supported Racket with donations via the Software Freedom Conservancy in the past. 
We would like to acknowledge your contribution by publishing your name(only) on a donors list on the Racket website. 
Would you please use this from to indicate your preference https://forms.gle/37dhKr2vYND7zx2S7 
 
Kind regards
```

Responses were used to populate the list in individuals.pm.html

the ‘37 anonymous donors’ were either uncontactable (no email, or email bounced), didn’t respond, or declined permission.

I was thinking of using Pyret to automate getting form data out of the google sheet associated with the form results
https://pyret.org/docs/horizon/gdrive-sheets.html

**Comment by LiberalArtist** [comment]
> i used the list of names to search for email addresses,

Do you mean the list you got from SFC didn't include email addresses, and you had to find them from other sources? If so, that definitely seems worth working with SFC to improve going forward. When I give to the SFC "sustainer" program, they [collect](https://sfconservancy.org/sustainer/) my permission to be [listed](https://sfconservancy.org/sponsors/#sustainers), my email, and even my t-shirt size and mailing address. Actually, IIRC they get the email address from PayPal (because I had to change the one for my listhost subscription), so I would have thought they'd get the same info for donations directed to Racket.

**Comment by spdegabrielle** [comment]
@LiberalArtist no such mechanism exists for member projects. I just verified by donating £0.82 
IMG_7840

PayPal is the only option - and I believe PayPal tells me when it needs to share my email or address to the ‘seller’.

(I also find it annoying that it says I am donating to SFC when my intention is to donate to racket)

**Comment by sorawee** [comment]
If you go to SFC website directly, it is possible to donate without using Paypal (and I would argue that it is more ergonomic than Paypal). In this form, it asks for contact information.

Screenshot 2024-01-20 at 6 50 21 AM

**Comment by spdegabrielle** [comment]
How?

I can’t see this option from either the racket donate page or the member projects  page
https://sfconservancy.org/projects/current/

**Comment by sorawee** [comment]
Screenshot 2024-01-20 at 7 09 44 AM

**Comment by LiberalArtist** [comment]
@sorawee I think the "Donate with Debit or Credit Card" option is also processed by PayPal, but doesn't require a PayPal account.

**Comment by spdegabrielle** [comment]
I see. PayPal handles the cc in that case but I don’t think it makes a difference - PayPal already has those details when I pay with my PayPal acct. 

Probably have to check to see if donors email is provided or available to member projects. I suspect only a member project committee member can ask that question. Even better: can the emails of donors be made available automatically & securely to enable automation?

**Comment by LiberalArtist** [comment]
I brought this thread to their attention on https://chat.sfconservancy.org and they'll see what the options are, though I wouldn't expect an answer over the weekend.

**Comment by sorawee** [comment]
We can extract GitHub sponsorship information via either the GitHub's [official GraphQL API](https://docs.github.com/en/graphql/reference/interfaces#sponsorable) or [this unofficial REST API](https://ghs.vercel.app/v2/sponsors/racket).

The official GraphQL API won't include past sponsorship though (unless the Racket GitHub account makes the query, IIUC). The unofficial REST API includes the past sponsorship information, but this is done by parsing the HTML page, which is in principle brittle, but might work well in practice.

**Comment by spdegabrielle** [comment]
I checked the a couple of other projects that use SFC, and the donation mechanism seems to be exactly the same.(no consent mechanism). I also reviewed a couple of what I believe are larger projects - git and squeak - and neither seem to list donors on their websites. 

That github sponsors ‘asks the question’ and has an API to support retrieving the data makes me think that it might be better to positions GitHub as the primary mechanism for sponsoring racket, with PayPal link and post listed as alternatives with the caveat that we are unable to acknowledge donations made by those methods. 
eg change the text at https://racket-lang.org/sfc.html to 

***

**In June 2018, Racket [became a member](https://sfconservancy.org/news/2018/jun/12/racketjoins/) of [Software Freedom Conservancy](https://sfconservancy.org/), a nonprofit organization that promotes open-source software.**

## Donate

* Donations, both in-kind and monetary, are used for hosting community infrastructure, administration, educational outreach, and community events such as RacketCon and Racket School.
* Best option: [sponsor Racket](https://github.com/sponsors/Racket).

Sponsoring via GitHub allows us to acknowledge [individuals](https://racket-lang.org/individuals.html)
for their generous support over the years.

many [individuals](https://racket-lang.org/individuals.html)
for their generous support over the years.


* You can also donate via PayPal or credit card  by clicking the button below.

CLICK HERE TO DONATE VIA PAYPAL

* We also accept checks drawn in US dollars from US banks. Make your check payable to “Software Freedom Conservancy, Inc.” and put “Directed donation: Racket” as the memo. Mail to:
* Software Freedom Conservancy
137 Montague St #380
Brooklyn NY 11201
* EIN: [41-2203632](tel:41-2203632)
* Thank you for supporting Racket!

***

**Comment by samth** [comment]
I can export a complete CSV of all sponsor transactions and that seems like the easiest way to get the relevant information.

**Comment by spdegabrielle** [comment]
> I can export a complete CSV of all sponsor transactions and that seems like the easiest way to get the relevant information.
@samth Does the SFC donor extract CSV include email addresses for the donors?

**Comment by spdegabrielle** [comment]
Closing this PR as it will not be accepted in its current form.

**Pull request closed without merging**
