### PR TITLE
Clarify the plt page some.

### PR DESCRIPTION
**Pull request by samth**
This PR removes the focus on PLT Design Inc, and changes the positioning a bit wrt the research aspects of the project.

### CODE REVIEW

**Comment by stamourv** [comment]
I don't like "recognized contributors". Are the others unrecognized?
That list is not really representative of Racket contributors anyway.

**Comment by bennn** [comment]
I like the title "Recognized Contributors", but I thinks it's important to say these people are recognized as shareholders in PLT design inc.

Two suggestion: (1) keep the original text, or (2) add a footnote / box that appears on hover to clarify what "special recognition" means.

**Comment by samth** [comment]
The goal here is to not make being a shareholder in a private company be an important part of contribution to Racket. Happy to take suggestions for other phrasings either for the section heading or for the text.

**Comment by stamourv** [comment]
Merged.

**Pull request closed without merging**
