### PR TITLE
Update 2024-10-31-racket-v8-15.md

### PR DESCRIPTION
**Pull request by spdegabrielle**
edited for clarity

### CODE REVIEW

**Comment by spdegabrielle** [comment]
@jbclements I'd like to include images but I'm stumped as to where to put them in the repo
save2htdpImage
restore

**Comment by sorawee** [comment]
https://github.com/racket/racket-lang-org/tree/master/blog/img

You can then include an image with `<caption>`

**Comment by spdegabrielle** [comment]
@jbclements Ok?

**Review by jbclements — APPROVED** [review]
LGTM, apologies for the delay!

**Comment by sorawee** [comment]
> I was confused because https://github.com/racket/racket-lang-org/blob/0e88696fc3898b5a0fefc4fc437901ed7336e098/blog/_src/posts/2024-02-08-racket-v8-12.md?plain=1#L9C1-L9C75 references a folder and file that do not appear in the repo

It's indeed confusing. @jbclements, could you tell what you did exactly, when you published https://github.com/racket/racket-lang-org/commit/9784d781e75de9f30629ac961bbee1789b01f0fe? My guess is that you uploaded the image file to S3 directly. Is that the case?

**Pull request merged**
