### PR TITLE
Update sfc.html.pm

### PR DESCRIPTION
**Pull request by spdegabrielle**
to prioritise Github sponsors as it supports acknowledging donors with their consent.

### CODE REVIEW

**Comment by samth** [comment]
I don't think we need to change this. People should feel free to donate how they feel, and acknowledgement then happens based on that.

**Comment by sorawee** [comment]
> People should feel free to donate how they feel

Well, currently we do encourage them to donate via SFC by saying it's the "best option". Maybe we shouldn't say that?

But I do not know if there is any agreement that Racket made with SFC. If the agreement is to encourage people to donate via SFC, I would agree that we shouldn't change anything.

**Comment by spdegabrielle** [comment]
I believe donations to Racket via GitHub Sponsors are going via SFC: https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/using-a-fiscal-host-to-receive-github-sponsors-payouts#

@samth would it be better if I changed the text to remove the word 'best' and just listed the options noting that GitHub Sponsors includes a 'consent to acknowledge' option?

FWIW the options are 
* SFC processing aa cheque you post them
* Paypal processing a either credit card or transfer from the donors PayPal account 
* GitHub Sponsors. via your GitHub account payment details which is either credit/debit card or PayPal

**Comment by LiberalArtist** [comment]
> FWIW the options are
> 
>     * SFC processing aa cheque you post them
> 
>     * Paypal processing a either credit card or transfer from the donors PayPal account
> 
>     * GitHub Sponsors. via your GitHub account payment details which is either credit/debit card or PayPal

The SFC has [additional options](https://sfconservancy.org/donate/), including bank/wire transfer and donation of stock, and many larger US companies have donation-matching programs that can effectively double a donation to SFC.

**Comment by spdegabrielle** [comment]
> > FWIW the options are
> > ```
> > * SFC processing aa cheque you post them
> > 
> > * Paypal processing a either credit card or transfer from the donors PayPal account
> > 
> > * GitHub Sponsors. via your GitHub account payment details which is either credit/debit card or PayPal
> > ```
> 
> The SFC has [additional options](https://sfconservancy.org/donate/), including bank/wire transfer and donation of stock, and many larger US companies have donation-matching programs that can effectively double a donation to SFC.

I’m not sure that is correct for member projects  such as racket. 

Further down the page linked by @LiberalArtist the following text can be found:

> Donate to our projects
> Finally, Conservancy also maintains directed donation programs for its [member projects](https://sfconservancy.org/projects/current/). Using the PayPal Donate button on that page is the easiest way to donate to a specific project. You can also designate a donation for a project in the memo line of a check or wire transfer.

Either way, closing as this PR is not seen as desirable.

**Pull request closed without merging**
