### PR TITLE
updated design for RC website

### PR DESCRIPTION
**Pull request by mbutterick**
@stamourv: I plan to refine this, but this will get you started.

### CODE REVIEW

**Comment by mbutterick** [comment]
(PS the two-tone lettering is generated by a [Racket program](https://github.com/mbutterick/racket-lang-org/blob/227fd60717be10a6d815f8f2651db5529dfa021d/rcon/2016/racketcon-font.rkt), of course)

**Comment by stamourv** [comment]
This is really cool!
The hatching on the sides makes me a bit dizzy, though. Maybe spacing the lines out would help?

**Comment by florence** [comment]
I have a *really* hard time reading the title lettering---whatever pattern matching my brain uses doesn't recognize a lot of the letters.

**Comment by rfindler** [comment]
I like it. Here are two concrete ideas for making it slightly easier to parse, visually speaking:

- make the parens round, or drop them, and maybe drop the word "sixth" at the top

- put a space in "also speaking"

**Comment by mbutterick** [comment]
I just noticed that the color animation doesn't work without HTTP. So [here it is](http://mbutterick.github.io/racket-lang-org/rcon/2016/).

**Comment by mbutterick** [comment]
I lightened the background image.

I could start the lettering in a more legible state, and then let the animations mess it up, rather than the more op-art starting condition.

As for the specific letters / words, that can be whatever you want. No parens on the top — is fine. "ALSOSPEAKING" could just be "SPEAKERS" (the goal is merely to use more letters than "KEYNOTE", thereby forcing the headline to be smaller)

**Comment by rfindler** [comment]
My comment about the parens is that I couldn't figure out what the words were on the top because I didn't recognize the parens as parens. I was trying to figure out what the 9th computer science thing was for a while before I gave up and went onto the next line and only then realized what was going on.

Overall, I like the page a lot and meant the suggestions to make it easier for people to figure out what that first line was.

**Comment by mbutterick** [comment]
Oh I don’t mind the suggestions at all. I just pushed a fix to [give the letters black outlines and simpler shapes](http://mbutterick.github.io/racket-lang-org/rcon/2016/). Better?

**Comment by rfindler** [comment]
Beautiful!

**Comment by rfindler** [comment]
My 9-year old son just wandered by and saw the front page and said "sixth racket con -- what is that? Is that a game? I hope so."  :)

**Comment by stamourv** [comment]
I love it!

Re the "speakers" section: I've been using "confirmed speakers" to convey that this is not the complete list, only the list so far. That's probably too long a title, especially with the large, animated text. Maybe we could just add "and more to come!" at the end?

**Comment by stamourv** [comment]
In any case, I can merge this version if you're happy with it, and do that change myself.

**Comment by mbutterick** [comment]
I just made that change. Yes, if you want to merge this version, I approve.

**Comment by mbutterick** [comment]
PS @stamourv I see you made some changes to the RCon home page since I forked it. You’ll want to bring those across.

**Comment by stamourv** [comment]
New design is merged, and mostly live.
For some reason, the live version insists on using last year's CSS, but a local version works just fine. Investigating.

**Comment by stamourv** [comment]
CSS issue fixed now. Had to purge a cache somewhere.

**Pull request closed without merging**
