### PR TITLE
the need to get rid of "Racket is a Scheme".

### PR DESCRIPTION
**Pull request by mfelleisen**
The line is too misleading. Adding "(kind of)" is a compromise. Better ideas welcome.

### CODE REVIEW

**Comment by rfindler** [comment]
Would it still be subtle if we wrote `Racket is a scheme` (lowercase)?

**Comment by samth** [comment]
What's the audience for this change? Are people currently looking at the "new-name.html" page, even though our web page doesn't link to it? If so, maybe we need a different page that explains things in a less 2010-centric way.

**Comment by mfelleisen** [comment]
I guess I forgot to CC you on the email from the HOPL/POPL meeting. 

Guy Steele googled "Racket Scheme" during the HOPL PC meeting and read this one bold-faced line aloud. Everyone looked at me and basically thought that he had just shown I was a liar when I said Racket isn't a Scheme it is an heir to Scheme (the next line). Nobody seemed to read the next, plain-text line. 

I also reviewed a CUP book proposal for a PL (311). The book is referring to our implementation as Racket Scheme. It uses several language and will show interpreters in both Racket and Python, possibly more. CUP wants to advertise it as a Racket Scheme book.

**Comment by samth** [comment]
The first sounds like a definite problem, and worth clarifying. Could we just use the literal next line: "Racket is a descendant of Scheme"?

The second I see plenty, but I've given up hope than anything we say can fix it generally. :(

**Comment by mfelleisen** [comment]
I'd be happy with this change too. 

As long as none of us are ever exposed to this "Racket is a Scheme" again, I am fine.

**Pull request merged**
