### PR TITLE
Add The Racket Guide to site as a book

### PR DESCRIPTION
**Pull request by spdegabrielle**
Add The Racket Guide to site as a book

### CODE REVIEW

**Comment by spdegabrielle** [comment]
explanation at https://github.com/racket/racket/issues/5029

**Comment by spdegabrielle** [comment]
Pretty?

image

**Comment by mfelleisen** [comment]
@mflatt s opinion matters here.

**Comment by spdegabrielle** [comment]
@mflatt 

my reason: 
----

**Is your feature request related to a problem? Please describe.**

There is a perception that there isn't a Racket equivalent to 'The C Programming Language', TSPL or ['The Rust Book'](https://doc.rust-lang.org/book/)
e.g. https://www.reddit.com/r/Racket/comments/1droxn6/htdp_claims_not_to_teach_you_racket_but/

**Describe the solution you'd like**
I'd like to see the The Racket Guide listed amongst the books on the Racket website.

**Describe alternatives you've considered**
I have considered other books such as *Realm of Racket*, *Racket programming the fun way* and others, but none fit the niche.

**Do you want to contribute to this feature**
yes. I am creating a pull request - I will add a link 

**[Optional] Additional context**

I created this issue to explain myself

**Comment by mflatt** [comment]
The motivate makes sense to me, and the change looks good. Any other opinions?

**Comment by rfindler** [comment]
Brilliant change!

**Comment by sorawee** [comment]
Yeah, I think this is a good idea. But is the description self-contradictory? (Detailed and overview.) 

I'm not a native English speaker though. If it sounds right to people, I would be ok with it.

**Pull request merged**
