### PR TITLE
resized versions of images for 8.15 blog post

### PR DESCRIPTION
**Pull request by spdegabrielle**
resized versions of images for 8.15 blog post

### CODE REVIEW

**Comment by sorawee** [comment]
I already fixed this in ae66639efe3c0890f0269e51368b5c261753984e...

**Comment by sorawee** [comment]
Ah, but I forgot to deploy the fix, so it's not showing up on https://blog.racket-lang.org/2024/11/racket-v8-15.html.

So now I just deployed the change. Should be available in 5 mins.

**Comment by sorawee** [comment]
OK to close the PR?

**Comment by spdegabrielle** [comment]
> Ah, but I forgot to deploy the fix, so it's not showing up on https://blog.racket-lang.org/2024/11/racket-v8-15.html.
> 
> Now I just deployed the change. Should be available in 5 mins.

thank you @sorawee looks great!

**Pull request closed without merging**
