### PR TITLE
introduce midpage slug

### PR DESCRIPTION
**Pull request by mbutterick**
One theme in the home-page feedback thus far is that it lacks a pithy “here’s what Racket is” sentence. OK internet, fair enough. I invite you to consider the text & presentation of this PR:

http://mbutterick.github.io/racket-lang-org/www/

Why put it in the middle? Because then it can also introduce the `#lang` boxes, which are unique to Racket (and thus important to show, but for the same reason could arguably be confusing)

Those who dislike the sentence, I invite you to propose better. With one condition: please *please* **please** can we steer clear of opaque jargon and generic claims. As David Ogilvy said, you can’t bore people into buying your product. 

IMO we should have something that would make sense even to the average *Realm of Racket* reader — and maybe even sound like … oh I don’t know … fun?

### CODE REVIEW

**Comment by mbutterick** [comment]
Examples of opaque jargon and generic claims. Put it to the test: without peeking, do you know which languages go in the blanks?

*“____ is a programming language designed to help programmers create flexible applications.”*

*“____ is a programming language that lets you work quickly and integrate systems more effectively.”*

*“____ is a dynamic, open source programming language with a focus on simplicity and productivity.”*

*“____ is a dynamic, functional language designed for building scalable and maintainable applications.”*

*“____ is a robust, practical, and fast programming language with a set of useful features that together form a simple, coherent, and powerful tool.”*

**Comment by mfelleisen** [comment]
> On Dec 27, 2016, at 8:15 PM, Matthew Butterick <notifications@github.com> wrote:
> 
> Examples of opaque jargon and generic claims. Put it to the test: without peeking, do you know which languages go in the blanks?
> 
> “____ is a programming language designed to help programmers create flexible applications.”
> 
> “____ is a programming language that lets you work quickly and integrate systems more effectively.”
> 
> “____ is a dynamic, open source programming language with a focus on simplicity and productivity.”
> 
> “____ is a dynamic, functional language designed for building scalable and maintainable applications.”
> 
> “____ is a robust, practical, and fast programming language with a set of useful features that together form a simple, coherent, and powerful tool.”
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

This is one heck of a pop quiz. I am sure I’d fail all the questions. I actually think that this is why ‘programming-language programming language’ is so cool. It stands out, it’s unique, it cuts to the bone, and nobody will ever mistake it for a Python slogan. 

I like your current sentence: 

"Racket is both a general-purpose programming language and a platform for implementing and deploying other languages. Make your dream language, or use one of the dozens already available, including these —"

and I think it is a critical and imperative addition to the site. 

1. When we wrote the Manifesto, we discussed ‘platform’ for a while but we came to the conclusion that it wasn’t just right. Perhaps we could replace it with ‘eco-system’ because JS also allows the creation of PLs (jQuery is a horrible example) but the key difference is that we can install a language into our eco-system w/o any ado and they can’t. For those who understand, hallelujah. For those who don’t, they will simply think we used an unusual word. 

2. I think I prefer ‘developing’ over ‘implementing’. One could for example use #lang redex to design the language’s ASTs and semantics, implement it in #lang racket. and deploy it. 

3. Instead of “both .X and Y” we could use “X as well as Y” so that the two ‘and’s don’t appear so close together in the sentence. 

4. Alternatively, but I am not sure I like this substantial rewrite, we could say “Racket, a general purpose programming language, is the first language in which developers create programming languages to solve problems. In Racket, you can program, you can make your own dream languages, and you can dive right into it all with one of the dozens already available, including these —“. 

— Matthias

**Comment by mbutterick** [comment]
Good suggestions, thank you. Though one tiny point:

> this is why ‘programming-language programming language’ is so cool. It stands out, it’s unique

Unfortunately it’s not. “Welcome to the [amazing world of Common Lisp](https://www.common-lisp.net/), the programmable programming language.”

**Comment by rfindler** [comment]
Wow-- they had that on their website in 2003:  

  https://web.archive.org/web/20030905213632/http://common-lisp.net/

**Comment by mfelleisen** [comment]
I sit corrected. We’re only a nice improvement over CL. Argh.

**Comment by rfindler** [comment]
Just because I was curious, I looked a little bit more and this phrase appears at least as early as 1991 in the September CACM issue in an article apparently entitled "LISP: introduction" by John Foderaro. It is available here: http://dl.acm.org/citation.cfm?id=114669.114670&coll=portal&dl=ACM

**Comment by mbutterick** [comment]
> the key difference is that we can install a language into our eco-system

Of course. This is why I have been (and will remain) an advocate for putting the “language-making” orientation front & center: **that** stands out, is unique, etc. No other PL can make that claim. It is more precise, concrete, and interesting than merely calling Racket “programmable”.

“Solve problems / make languages” may be too short, but it was intended as the shortest possible summary of the [topic sentence](http://www.ccs.neu.edu/home/matthias/manifesto/) of the Manifesto.

From there, I also like:

> Racket is a programming language for creating new programming languages

But in isolation, it makes Racket sound strictly like a DIY kit rather than something that can work out of the box. IOW, the benefits of Racket as a language-making ecosystem are enjoyed not only by those who want to make a language, but also by those who might like to choose among a family of Racket-hosted languages, large and small.

**Comment by mfelleisen** [comment]
Perhaps I stole it, subconsciously at least. Sad :(

**Comment by rfindler** [comment]
On Wed, Dec 28, 2016 at 6:55 PM, Matthias Felleisen <
notifications@github.com> wrote:

>
> Perhaps I stole it, subconsciously at least. Sad :(
>
>
There is nothing new under the sun. (Insert rant about bogus academic
currency here.) And just to prove that point one more time, I thought _I_
was the one that subconsciously stole it! (YIkes.)

**Comment by mfelleisen** [comment]
> On Dec 28, 2016, at 7:51 PM, Matthew Butterick <notifications@github.com> wrote:
> 
> the key difference is that we can install a language into our eco-system
> 
> Of course. This is why I have been (and will remain) an advocate for putting the “language-making” orientation front & center: that stands out, is unique, etc. No other PL can make that claim. It is more precise, concrete, and interesting than merely calling Racket “programmable”.
> 
> “Solve problems / make languages” may be too short, but it was intended as the shortest possible summary of the topic sentence <http://www.ccs.neu.edu/home/matthias/manifesto/> of the Manifesto.
> 

It is, it is. It just sounds so much more like a slogan from the 1960s than what we are used to seeing. 


> From there, I also like:
> 
> Racket is a programming language for creating new programming languages
> 
> But in isolation, it makes Racket sound strictly like a DIY kit rather than something that can work out of the box. IOW, the benefits of Racket as a language-making ecosystem are enjoyed not only by those who want to make a language, but also by those who might like to choose among a family of Racket-hosted languages, large and small. 
> 

Absolutely. That’s why I rewrote the introduction in my next draft (for a submission to CACM): 

   http://www.ccs.neu.edu/home/matthias/cacm/Problems_vs_Programming_Languages.html

See last paragraph. 

Today I wrote in a different email thread something that could be translated to here like this: 

```In the near future, developers will create languages to solve problems. 
They will certainly need a general-purpose language for basic tasks, but 
for challenging tasks, they will use extensible languages that will make it 
easy to add abstractions that reduce, or even eliminate, the gap between 
ideas in the problem domain and the linguistic constructs offered. The 
future has arrived. Now there is Racket and the dream has come true.’’’'

**Comment by lexi-lambda** [comment]
I agree strongly with most of the conversation here, so I will only add one thing: I would caution against putting *too* much emphasis on `#lang` when `syntax/parse` is probably the more useful tool for the average user.

Obviously, that language is too Racket-specific to be meaningful to anyone new, but my general point is that “programmable programming language” elicits more of an “extensible” vibe, while the current copy emphasizes making entirely new languages. In the Racket world, there is much more overlap than one might think, but newcomers won’t know that. Racket’s macro system makes it possible to make embedded languages that cooperate in much more interesting ways than `#lang`s can (by virtue of being significantly less powerful), and I think that’s a somewhat more appealing feature than the ability to make entirely distinct languages with their own source syntax.

I guess I’m saying that the current wording—“make your dream language”—sells Racket short! The idea is not that Racket is a toolkit for making a bunch of different compilers, but that it is an ecosystem of languages **that can work together**, as Matthias mentions. Your wording is appealing to me as a language designer, but even though most people aren’t language designers, Racket’s language building facilities can still benefit them; I think emphasizing that a little more would go a long way.

**Comment by mfelleisen** [comment]
'weave your dream language into the web of Racket’ (Alexis you’re too young to remember a song called ‘dream weaver’, heck, all of you might be :) 

To Alexis specifically, I think #lang and syntax-parse are at about the same level of usefulness. #lang is the critical organizational tool to creating a language by adding/subtracting/overriding constructs but also adding context-sensitive analysis and compilation. syntax-parse is a tool that helps you with all of these (except for subtracting), so you will think you’re using it more but w/o #lang properly done, you’d just keep on stumbling into the old CL and Scheme bugs.

**Comment by mbutterick** [comment]
> embedded languages that cooperate in much more interesting ways [using `syntax/parse`]

What are some examples that exist on the package server?

**Comment by lexi-lambda** [comment]
- [anaphoric](http://docs.racket-lang.org/anaphoric/index.html) — Uses syntax parameters to implement anaphoric conditionals.
- [`sequence` from collections](http://docs.racket-lang.org/collections/collections-api.html#%28form._%28%28lib._data%2Fcollection..rkt%29._sequence%29%29) — Adds the ability to pattern match on arbitrary sequences by extending the `match` form.
- [fancy-app](https://github.com/samth/fancy-app) — Adds Scala-style “magic” lambdas to arbitrary languages by just modifying `#%app`.
- [`do` from functional](http://docs.racket-lang.org/functional/interfaces.html#%28form._%28%28lib._data%2Fmonad..rkt%29._do%29%29) — Provides a monadic `do` notation that permits arbitrary internal definitions, including user-defined macros that expand to internal definitions.
- [generic-bind](http://docs.racket-lang.org/generic-bind/index.html) — Provides user-extensible binding forms in the style of `match`.
- [lens](http://docs.racket-lang.org/lens/index.html) — Uses static structure type information to automatically generate lenses on user-defined datatypes.
- [parsack](http://docs.racket-lang.org/parsack/index.html) — Implements the `parser-compose` and `parser-seq` mini-DSLs for composition of parsers.
- [threading](http://docs.racket-lang.org/threading/index.html) — Adds Clojure-style threading macros that cooperate with languages’ `#%app` and allow adjusting the threading position.
- [`dispatch-rules` from web-server](http://docs.racket-lang.org/web-server/dispatch.html#%28form._%28%28lib._web-server%2Fdispatch..rkt%29._dispatch-rules%29%29) — Adds a user-extensible HTTP routing system using bidirectional pattern matching.

Not 100% of these are implemented using `syntax/parse`, but most of them are, and those that aren’t could be, they just aren’t for historical reasons. There are probably many more, but this was just a sampling of some of the interesting ones I already knew of.

The really nice thing about ordinary macros is that they compose. You can use them in many different `#lang`s, and you can nest them within each other. Some of them are even extensible, like `match`, `~define`, and `dispatch-rules`. Even `syntax-parse` itself is extensible.

Also, I have found it frequently useful to write local macros specific to a particular application of mine. These macros won’t end up in a package because they wouldn’t be useful outside of my domain, but that’s sort of the point—they’re highly specialized domain specific languages that I wrote in a few minutes. Writing a `#lang` is great, but it’s a lot more work, and you don’t get the ability to compose them together as easily. It serves a different purpose. Racket has both.

**Comment by gregid** [comment]
How about a mutation of the above:

"Use Racket as a [general-purpose programming language](http://docs.racket-lang.org/quick/index.html) with vast [ecosystem](https://pkgs.racket-lang.org/), add innovative [language constructs](https://docs.racket-lang.org/syntax/stxparse.html) to solve your problems or even make your [dream language](http://docs.racket-lang.org/guide/languages.html)  that will easily interact with dozens of existing languages, including these:"

**Comment by mbutterick** [comment]
“Dream language” — I love it.

http://mbutterick.github.io/racket-lang-org/www/

**Pull request merged**
