### PR TITLE
RacketCon 2017 web page

### PR DESCRIPTION
**Pull request by mbutterick**

### CODE REVIEW

**Comment by mbutterick** [comment]
This PR makes the main RacketCon page look like this: http://mbtype.com/2017/index.html

**Comment by bennn** [comment]
This is great.

Can you add a "stop" button?
Or have non-wavy text appear on mouse hover?

**Comment by rfindler** [comment]
Triiiiipy! I like it.

(The 2016 link on the bottom is broken.)

Robby

**Comment by mbutterick** [comment]
@rfindler: The RC 2016 link will work after the site is rebuilt, and the 2016 site is moved into its new archival folder.

**Comment by mbutterick** [comment]
@bennn: I’ll look into it, as they say these days

**Comment by LeifAndersen** [comment]
FYI, this website breaks screen readers.

I mean, they can still work, but it basically repeats the text over and over and over again before you get to any content. ;)

**Comment by LeifAndersen** [comment]
So, here's a thought, and I won't be offended if you completely reject it.

I think you can keep the cool floaty effect while also making it easier to read for people who use screen readers. Namely:

keep the floating text, but maybe only have one copy of each word floating around, rather than 3-4 copies. That will make the text look much clearer, still look cool (you could even have it change colors if you want), but also not become a garbled mess for people without good vision.

Just a thought anyway.

**Comment by rfindler** [comment]
Is there a way to tell the screen readers that "these 4 copies of that text are to be ignored" that could make screen readers work will still preserving the awesomeness of the current design?

PS: I showed this to our kids and they loved it. They were mesmerized and then said "wow, that's cool. How did he make that?".

**Comment by LeifAndersen** [comment]
Honestly, I have no idea.

Although I can say that as is, the text is kind of hard on my eyes.

**Comment by mbutterick** [comment]
The screen-reader issue was also raised in issue #37, with no resolution. As before, I’m willing to make adjustments — for most browser-layout issues, there’s some kind of workaround — if someone wants to make a PR, tell me what the workaround should be, or just point me to current information about tailoring HTML/CSS to screen readers.

**Comment by mbutterick** [comment]
> They were mesmerized and then said "wow, that's cool. How did he make that?"

@rfindler Maybe it’s time to have the Racket Talk with your kids.

**Comment by lexi-lambda** [comment]
@mbutterick The relevant HTML attributes for accessibility are defined by [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA), which provides control over how screen readers and other devices interpret web pages. In this case, I think you could just add `aria-hidden="true"` to the duplicate elements to help screen readers cope.

**Comment by mbutterick** [comment]
Thanks. That’s done. 67358b2b7caa3529aa0f053d4b92e2e1e98b4783

**Comment by stamourv** [comment]
It's live!

**Comment by bennn** [comment]
@mbutterick I just read this quote on Eelco Visser's [homepage](http://eelcovisser.org/) and thought of you:

> MetaBorg provides generic technology for allowing a host language (collective) to incorporate and assimilate external domains (cultures) in order to strengthen itself. The ease of implementing embeddings makes resistance futile.

**Pull request merged**
