### PR TITLE
First stab at 2022 page

### PR DESCRIPTION
**Pull request by jessealama**

### CODE REVIEW

**Comment by jessealama** [comment]
This is a quite incomplete first go at the 2022 RacketCon page. The intention is to get the ball rolling and start gathering data using a pre-registration form (hosted on Typeform) so that we can make an educated decision about how to price the event. We don't know if we're expecting 20 or 200 people! As invited speakers start to form, and the Friday hackathons start to take shape, this page will be updated.

**Comment by jessealama** [comment]
I’ll attach the generated index.html in a bit.

**Comment by jessealama** [comment]
[index.html.gz](https://github.com/racket/racket-lang-org/files/8998281/index.html.gz)

**Comment by jessealama** [comment]
(HTML files aren't directly supported, but you can upload a gzip'd HTML file.)

**Comment by jessealama** [comment]
cc @jeapostrophe

**Comment by jeapostrophe** [comment]
Looks fine. @mflatt needs to push it AFAIK

**Comment by mflatt** [comment]
Ok if I change the sources to produce this variant?
[index.html.gz](https://github.com/racket/racket-lang-org/files/9002690/index.html.gz)

The indentation of `(twelfth RacketCon)` looked strange on my machine due to the leading space and line break, and "Department of Computer Science, Brown University, Providence, Rhode Island, USA" seemed large and long, so the changes adjust those parts.

**Comment by jessealama** [comment]
@mflatt I also noticed the weird spacing but didn't know right away how to fix it. Thanks!

**Comment by jessealama** [comment]
I’ve changed a couple of things based on feedback from Shriram.

**Comment by mflatt** [comment]
Ok, I'll merge and push. I'll also add you as a collaborator on this repo, so you don't have to go through PRs, but I guess you'll still need to ping me to push changes.

**Pull request merged**
