### PR TITLE
Try harder to detect platforms.

### PR DESCRIPTION
**Pull request by samth**
See https://groups.google.com/forum/#!topic/racket-users/XAUGE1q793w for background.

### CODE REVIEW

**Comment by jbclements** [comment]
This looks clear and sensible to me, but I do have one question: Can I ask what the `@";"` is doing? Is that some terrible JS-ism that I should know about?

**Comment by samth** [comment]
It's inserting a real semicolon in the output since this is scribble-generating-js.

**Comment by jbclements** [comment]
so the predicate that succeeds just happens to effectfully generate stdout? Yikes. Ah well.

**Comment by jbclements** [comment]
In the spirit of erring on the side of getting things done, I'm going to go ahead and merge this pull request. Someone please tell me if I'm breaking implicit protocol like I usually do :).

**Pull request merged**
