### PR TITLE
add missing channels to first community section.

### PR DESCRIPTION
**Pull request by spdegabrielle**

### CODE REVIEW

**Comment by spdegabrielle** [comment]
@jbclements your review would be appreciated.

**Comment by jbclements** [comment]
Looking at the existing content of this section, I think it's mostly oriented toward possible contributors to development (hence the inclusion of the github link). I think a better name here might be just "Open Source". I would then be inclined to include the Contributing link, the github link, the discourse link, and maybe nothing else. 

I think there's a larger question, about whether the community tab should be in the topmost group.



Thoughts? @samth ? @jeapostrophe ? @rfindler ? @mflatt ? @mfelleisen ?

**Comment by mfelleisen** [comment]
My idea was that the two communities -- users and devs -- were interwoven and engaged.  The word "vibrant" seemed to apply to both. I also thought that "vibrant community" attracts others to participate. -- As Jay said somewhere though, Matthias did a miserable job on some aspects of this page and so we told him what to do :-) Perhaps there's more there than my own thinking. 

Given the interest in Rhombus, I think "dev" is even more vibrant now, but Stephen's engagement has also made users participate much more.  What do you think of two tabs: "devs" and "users".  The words are shorter, so they'd fit.  They lack "vibrant" but that could be brought back somewhere else. 

I guess this suggests a minor but not insignificant re-do of this section.

**Comment by spdegabrielle** [comment]
> My idea was that the two communities -- users and devs -- were interwoven and engaged. The word "vibrant" seemed to apply to both. I also thought that "vibrant community" attracts others to participate. -- As Jay said somewhere though, Matthias did a miserable job on some aspects of this page and so we told him what to do :-) Perhaps there's more there than my own thinking.
> 
> Given the interest in Rhombus, I think "dev" is even more vibrant now, but Stephen's engagement has also made users participate much more. What do you think of two tabs: "devs" and "users". The words are shorter, so they'd fit. They lack "vibrant" but that could be brought back somewhere else.
> 
> I guess this suggests a minor but not insignificant re-do of this section.

I wholeheartedly support this and would even take a crack at writing it up - but I lack the bandwidth to implement. I’m not familiar with the markup language and I don’t have time to learn it properly.  Maybe when I write a book.

I’ll close this PR in the interim.

**Pull request closed without merging**
